DATASET_NAME: 'SAIR.ELP'
OWNER: 'SAIR lab - KCL'
VOC_DIR: 'voc/'
XML_PREFIX: 'aa2.xml'
RGB_PREFIX: '/head-rgb/bbox'
D_PREFIX: 'default'
AID_IMG: 'f-formations.png'
CLASSES: ["N/A", "L-arrangement", "face-to-face", "side-by-side", "semi-circular", "rectangular"]
BBOX_PREFIX: '/home/viktor/Desktop/actanno/actanno-2/kcltestimages/bbox_rgb'