DATASET_NAME: 'SAIR.ELP'
OWNER: 'SAIR lab - KCL'
VOC_DIR: 'voc/'
XML_PREFIX: 'aaa.xml'
RGB_PREFIX: '/head-center/frame'
D_PREFIX: 'default'
AID_IMG: 'f-formations.png'
CLASSES: ["N/A", "L-arrangement", "face-to-face", "side-by-side", "semi-circular", "rectangular"]
