DATASET_NAME: 'SAIR.ELP'
OWNER: 'SAIR lab - KCL'
VOC_DIR: 'voc/'
XML_PREFIX: '/seg1_human.xml'
#HUM_TRA_PREFIX: 'default'
RGB_PREFIX: '/bbox'
AID_IMG: '/keybind_humanno.png'
CLASSES: ["N/A"]
BBOX_PREFIX: '/home/viktor/Desktop/actanno/actanno-2/human-notation/seg1_final'
FNAME_PREFIX: 'bbox'

