DATASET_NAME: 'SAIR.ELP'
OWNER: 'SAIR lab - KCL'
VOC_DIR: 'voc/'
XML_PREFIX: '/seg2_human.xml'
#HUM_TRA_PREFIX: 'default'
RGB_PREFIX: '/frame'
AID_IMG: 'keybind_humanno.png'
CLASSES: ["N/A"]
BBOX_PREFIX: '/home/viktor/Desktop/actanno-v3/person_level_outputs'
FNAME_PREFIX: 'frame'

# python actanno-v3-indexassign.py ./supporting_files/indexassign/ /home/viktor/Documents/seg2-groups/