DATASET_NAME: 'SAIR.ELP'
OWNER: 'SAIR lab - KCL'
VOC_DIR: 'voc/'
XML_PREFIX: '/HtoG.xml'
# HUM_TRA_PREFIX: 'default'
RGB_PREFIX: '/bbox'
AID_IMG: 'default'
CLASSES: ["N/A"]
BBOX_PREFIX: '/home/viktor/Desktop/actanno/actanno-2/human-notation/bboxes'